waste_management/waste_management/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from waste.views import indexview,login_view,userRegistration
from waste import admin_urls,user_urls,collector_urls
from waste.admin_views import product_list
from waste.views import shop,view_product,CheckPincodeView,Check

urlpatterns = [
    path('admin/',admin_urls.urls()),
    path('',indexview.as_view()),
    path('Check',Check.as_view()),
    path('login',login_view.as_view()),
    path('UserRegister',userRegistration.as_view()),
    path('user/',user_urls.urls()),
    path('collector/',collector_urls.urls()),
    path('Shop',shop.as_view()),
    path('viewproducts',product_list.as_view()),
    path('Product',view_product.as_view()),
    path('check_pincode/', CheckPincodeView.as_view(), name='check_pincode'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG :
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_URL)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waste_management/waste/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
#creating tables in django
class user_Registration(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    mobile=models.CharField(null=True,max_length=100) 
    address=models.CharField(null=True,max_length=100) 
    pincode=models.CharField(null=True,max_length=20)
    password=models.CharField(null=True,max_length=100)
    name=models.CharField(null=True,max_length=100)
    email=models.CharField(null=True,max_length=100)
    point=models.IntegerField(default=0)

class userType(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    type=models.CharField(null=True,max_length=100)

class collector_Registration(models.Model):
    mobile=models.CharField(null=True,max_length=100)
    address=models.CharField(null=True,max_length=100)
    password=models.CharField(null=True,max_length=100)
    name=models.CharField(null=True,max_length=100)
    email=models.CharField(null=True,max_length=100)
    collector_id=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    
class products(models.Model):
    name=models.CharField(max_length=100,null=True)
    rate=models.IntegerField(null=True)
    point=models.IntegerField(null=True)
    desc=models.CharField(max_length=200,null=True)
    image=models.ImageField(null=True,upload_to='images')
    status=models.IntegerField(null=False)
    
class stock_his(models.Model):
    product=models.ForeignKey(products,on_delete=models.CASCADE)
    stock=models.IntegerField(null=True)

class category(models.Model):
    name=models.CharField(max_length=100)
    point=models.IntegerField(null=True)

class waste_pickup(models.Model):
    userid=models.ForeignKey(user_Registration,on_delete=models.CASCADE,null=True)
    collector=models.ForeignKey(collector_Registration,on_delete=models.CASCADE,null=True)
    status=models.CharField(max_length=100,default='requested')
    rdate=models.DateField(default=timezone.now)
    pdate=models.DateField(null=True)


class CollectionHistory(models.Model):
    pid = models.ForeignKey(waste_pickup, on_delete=models.CASCADE)
    category = models.ForeignKey(category, on_delete=models.CASCADE)
    weight = models.FloatField(null=True)
    point = models.IntegerField(null=True)

class Purchase(models.Model):
    user=models.ForeignKey(user_Registration,on_delete=models.CASCADE,null=True)
    date=models.DateField(default=timezone.now)
    product=models.ForeignKey(products,on_delete=models.CASCADE)
    mobile=models.CharField(null=True,max_length=100)
    address=models.CharField(null=True,max_length=100)
    pincode=models.CharField(null=True,max_length=20)
    quantity=models.CharField(null=True,max_length=1,default=1)
    REDEEM='R'
    PURCHASE='P'
    CHOICE=[(REDEEM,'Redeem'),(PURCHASE,'Purchase')]
    type=models.CharField(max_length=2,choices=CHOICE)
    total=models.IntegerField(null=True)
    status=models.CharField(max_length=20,null=True,default='Ordered')
    
class OrderUpdates(models.Model):
    order=models.ForeignKey(Purchase,on_delete=models.CASCADE,null=True)
    date=date=models.DateField(default=timezone.now)
    status=models.CharField(max_length=20,null=True,default='Ordered')
    update=models.CharField(null=True,max_length=100)

class Comaplaints(models.Model):
    user=models.ForeignKey(user_Registration,on_delete=models.CASCADE,null=True)
    subject=models.CharField(null=True,max_length=100)
    complaint=models.CharField(null=True,max_length=200)
    rdate=models.DateField(default=timezone.now)
    sdate=models.DateField(null=True)
    status=models.CharField(max_length=20,null=True,default='Pending')

class locations(models.Model):
    pincode=models.CharField(max_length=10,null=True)

waste_management/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>RevivE</title>
  <link rel="stylesheet" href="{% static 'css/shop.css' %}">
	<link rel="icon" href="{% static 'img/Fevicon.png' %}" type="image/png">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/fontawesome/css/all.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendors/themify-icons/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/nice-select/nice-select.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<header class="header_area">
    <div class="main_menu">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
        </td>
        <a class="navbar-brand logo_h" href="index.html" style="max-width: 100px;">
          <img src="{% static 'img/logo.png' %}" alt="" style="max-height: 40px;">
        </a>        
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
            <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
              <li class="nav-item "><a class="nav-link" href="/user">Home</a></li>
              <li class="nav-item "><a href="Shop" class="nav-link ">Shop</a></li>
				{% if uid.last_name == '1' %}
				<li class="nav-item submenu dropdown "><a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
					aria-expanded="false" href="#">Waste Pickup's</a>
					<ul class="dropdown-menu">
						<li class="nav-item"><a class="nav-link" href="PickupRequest">Request&nbsp;For&nbsp;Pickup</a></li>
						<li class="nav-item"><a class="nav-link" href="PointHistory">Points History </a></li>
						<li class="nav-item"><a class="nav-link" href="ReqestHistory">Track Request's</a></li>
					  </ul>
				
				</li>{% endif %}
              <li class="nav-item submenu dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                  aria-expanded="false">Profile</a>
                <ul class="dropdown-menu">
                  <li class="nav-item"><a class="nav-link" href="ViewProfile">View Profile</a></li>
                  <li class="nav-item"><a class="nav-link" href="EditProfile">Edit Profile</a></li>
				  <li class="nav-item"><a class="nav-link" href="OrderHistory">OrderHistory</a></li>
                </ul>
							</li>
							<li class="nav-item submenu dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                  aria-expanded="false">Pages</a>
                <ul class="dropdown-menu">
                  <li class="nav-item"><a class="nav-link" href="/login">Log Out</a></li>
                  <li class="nav-item"><a class="nav-link" href="ComplaintRegister">Register Complaint</a></li>
                  <li class="nav-item"><a class="nav-link" href="TrackComplaints">Track Complaints</a></li>
                </ul>
              </li>


			{% if  uid.last_name == '4'%}
			  <li class="nav-item "><a class="nav-link "  href="JoinUs">Join us</a></li>
			{% endif %}
            </ul>

           
          </div>
        </div>
      </nav>
    </div>
  </header>

  {% block content %}
  
  {% endblock  %}

    
  <!--================ Start footer Area  =================-->	
	<footer class="footer">
	
		<div class="footer-bottom">
			<div class="container">
				<div class="row d-flex">
					<p class="col-lg-12 footer-text text-center">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
				</div>
			</div>
		</div>
	</footer>
	<!--================ End footer Area  =================-->
	<script src="{% static 'vendors/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'css/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendors/skrollr.min.js' %}"></script>
	<script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
	<script src="{% static 'vendors/nice-select/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'vendors/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'vendors/mail-script.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>





</body>
</html>

waste_management/templates/user/bill.html
<style>
.top_rw{ background-color:#f4f4f4; }
	.td_w{ }
	button{ padding:5px 10px; font-size:14px;}
    .invoice-box {
        max-width: 890px;
        margin: auto;
        padding:10px;
        border: 1px solid #eee;
        box-shadow: 0 0 10px rgba(0, 0, 0, .15);
        font-size: 14px;
        line-height: 24px;
        font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color: #555;
    }
    .invoice-box table {
        width: 100%;
        line-height: inherit;
        text-align: left;
		border-bottom: solid 1px #ccc;
    }
    .invoice-box table td {
        padding: 5px;
        vertical-align:middle;
    }
    .invoice-box table tr td:nth-child(2) {
        text-align: right;
    }
    .invoice-box table tr.top table td {
        padding-bottom: 20px;
    }
    .invoice-box table tr.top table td.title {
        font-size: 45px;
        line-height: 45px;
        color: #333;
    }
    .invoice-box table tr.information table td {
        padding-bottom: 40px;
    }
    .invoice-box table tr.heading td {
        background: #eee;
        border-bottom: 1px solid #ddd;
        font-weight: bold;
		font-size:12px;
    }
    .invoice-box table tr.details td {
        padding-bottom: 20px;
    }
    .invoice-box table tr.item td{
        border-bottom: 1px solid #eee;
    }
    .invoice-box table tr.item.last td {
        border-bottom: none;
    }
    .invoice-box table tr.total td:nth-child(2) {
        border-top: 2px solid #eee;
        font-weight: bold;
    }
    @media only screen and (max-width: 600px) {
        .invoice-box table tr.top table td {
            width: 100%;
            display: block;
            text-align: center;
        }
        .invoice-box table tr.information table td {
            width: 100%;
            display: block;
            text-align: center;
        }
    }
    /** RTL **/
    .rtl {
        direction: rtl;
        font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
    }
    .rtl table {
        text-align: right;
    }
    .rtl table tr td:nth-child(2) {
        text-align: left;
    }
</style>
<div class="invoice-box">
    <table cellpadding="0" cellspacing="0">
    <tr class="top_rw">
       <td colspan="2">
          <h2 style="margin-bottom: 0px;"> Invoice </h2>
          <span style=""> Number: 27B00032991LQ354  </span>
       </td>
        <td  style="width:30%; margin-right: 10px;">
            Order Id: {{pur.id}}
       </td>
    </tr>
        <tr class="top">
            <td colspan="3">
                <table>
                    <tr>
                        <td>
                        <b> Sold By: were Enterprises </b> <br>
                            wr Pvt. Ltd. Plot No. A5 Indian Corporation <br>
Warehouse Park Village Dive-anjur, Bhiwandi, Off <br>
Nh-3, Near Mankoli Naka, District Thane, Pin Code :686693
421302 <br>
Mumbai, Maharashtra - 421302 <br>
PAN: AALFN0535C <br>
GSTIN: 27AALFN0535C1ZK <br>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr class="information">
              <td colspan="3">
                <table>
                    <tr>
                        <td colspan="2">
                        <b> Shipping Address: {{ pur.user.name}} </b> <br>
                            {{pur.address}}<br>
                            {{pur.mobile}}<br>
                            {{pur.pincode}}<br>
                        </td>
                        <td> <b> Billing Address: werepoint </b><br>
                            Acme Corp.<br>
                            John Doe<br>
                            were@example.com
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
                        <td colspan="3">
        <table cellspacing="0px" cellpadding="2px">
        <tr class="heading">
            <td style="width:25%;">
                ITEM
            </td>
            <td style="width:10%; text-align:center;">
                QTY.
            </td>
            <td style="width:10%; text-align:right;">
                COST
            </td>
             <td style="width:15%; text-align:right;">
               PURCHASE  TYPE
            </td>
        </tr>
        <tr class="item">
           <td style="width:25%;">
               {{pur.product.name}}
            </td>
            <td style="width:10%; text-align:center;">
                {{pur.quantity}}
            </td>
            <td style="width:10%; text-align:right;">
                {{pur.product.rate}}
            </td>
            
             <td style="width:15%; text-align:right;">
                {{pur.get_type_display}}
            </td>
        </tr>
        </td>
        </table>
        <tr class="total">
              <td colspan="3" align="right">  Total :  <b> {{ pur.total }}{% if pur.type == 'R' %} W-Points {% else %} ₹{% endif %} </b> </td>
        </tr>
        <tr>
           <td colspan="3">
             <table cellspacing="0px" cellpadding="2px">
                <tr>
                    <td width="50%">
                    <b> Declaration: </b> <br>
                                        We declare that this invoice shows the actual price of the goods
                                        described above and that all particulars are true and correct. The
                                        goods sold are intended for end user consumption and not for resale.
                    </td>
                    <td>
                     * This is a computer generated invoice and does not
                      require a physical signature
                    </td>
                </tr>
                 <tr>
                    <td width="50%">
                    </td>
                    <td>
                         <b> Authorized Signature </b>
                        <br>
                        <br>
                        ...................................
                        <br>
                        <br>
                        <br>
                    </td>
                </tr>
             </table>
           </td>
        </tr>
    </table>
</div>

waste_management/templates/user/checkout.html
{% extends 'user/base.html' %}
{% block content %} 
{% load static %}

<style>
  .hide {
      display: none;
  }
</style>

<!-- ================ start banner area ================= --> 
<section class="blog-banner-area" id="category">
  <div class="container h-50">
    <div class="blog-banner">
      <div class="text-center">
        <h1>Product Checkout</h1>
        <nav aria-label="breadcrumb" class="banner-breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Checkout</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>
<!-- ================ end banner area ================= -->


<!--================Checkout Area =================-->
<section class="checkout_area section-margin--small">
  <div class="container">
      
      <div class="billing_details">
          <div class="row">
              <div class="col-lg-8">
                  <h3>Billing Details</h3>
                  
                  <form class="row contact_form" method="post" action="{% url 'user:checkout' %}" novalidate="novalidate">
                    {% csrf_token %}
                    <div class="form-group">
                      <p style='color:black'>{{ user.name  }} <br> {{ user.address }} <br> {{user.pincode }} <br> +91 {{user.mobile }} </p>
                      <br>
                      <input type="checkbox" id="check" name="check" onchange="toggleBillingDetails()"><span >Use this address </span>
                    </div>
                    <br>
                      <input type="hidden" name="id" value="{{ pd.id }}">

                      <div class="col-md-12 form-group p_star">
                          <input type="text" class="form-control" id="add1" name="add1" placeholder="Address line 01">
                      </div>
                      <div class="col-md-12 form-group p_star">
                          <input type="text" class="form-control" id="add2" name="add2" placeholder="Address Line 02">
                      </div>
                      <div class="col-md-6 form-group ">
                        <input type="text" class="form-control" id="number" name="number" placeholder="Phone">
                    </div>  
                      <div class="col-md-12 form-group">
                          <input type="text" class="form-control" id="zip" name="zip" placeholder="Postcode/ZIP">
                      </div>
              
                      </div>
                      <div class="col-lg-4">
                          <div class="order_box">
                              <h2>Your Order</h2>
                              <ul class="list list_2">
                                  <li><h4>Product <span>Total</span></h4></li>
                                  <li><a>{{pd.name}} <span class="middle"></span> <span class="last">
                                      {% if opt == 'redeem' %}
                                      {{pd.point}} W-Points 
                                      {% else%}
                                      ₹ {{pd.rate}} x {{qty}} </span> </a></li>
                                      {% endif %}
                              </ul>
                              <br>
                              <ul class="list list_2">
                                  <li><a>Total <span class='last'>     {% if opt == 'redeem' %}
                                      {{pd.point}} W-Points 
                                      {% else%}
                                      ₹ {{total}} </a></li>
                                      {% endif %}
                              </ul>
                              <br>
                              <div class="creat_account">
                                  <input type="checkbox" id="f-option4" name="selector" required >
                                  <label for="f-option4">I’ve read and accept the </label>
                                  <a href="#">terms & conditions*</a>
                              </div>
                                <ul class="list list_2">
                                  {% if opt == 'redeem' %}
                                <li><input type="submit" class="button button-paypal" value="Pay with W-Points" name='redeem'></li><br>
                                {% else %}
                                  <input type="hidden"  name ="qty" value={{qty}}>

                                <li><input type="submit" class="button button-paypal" value="Pay with Cash" name='purchase' ></li>
                                {% endif %}
                                </ul>
                          </div>
                      </div>


                    </form>
          </div>
      </div>
  </div>
</section>
<!--================End Checkout Area =================-->

<!-- Add the <script> tag to include JavaScript -->
<script>
  function toggleBillingDetails() {
      // Get the checkbox element
      var checkbox = document.getElementById("check");
  
      // Get the input fields
      var numberInput = document.getElementById("number");
      var add1Input = document.getElementById("add1");
      var add2Input = document.getElementById("add2");
      var zipInput = document.getElementById("zip");
  
      // If the checkbox is checked, hide the input fields
      if (checkbox.checked) {
          numberInput.classList.add("hide");
          add1Input.classList.add("hide");
          add2Input.classList.add("hide");
          zipInput.classList.add("hide");
      } else {
          // If the checkbox is unchecked, show the input fields
          numberInput.classList.remove("hide");
          add1Input.classList.remove("hide");
          add2Input.classList.remove("hide");
          zipInput.classList.remove("hide");
      }
  }
  </script>
  
  <!-- ... (other HTML code) ... -->

{% endblock %}

waste_management/templates/user/complaintstatus.html
{% extends 'user/base.html' %}
{% block content %}
<h1 align="center" >Complaint Status </h1>
<table class="table table-bordered table-hover">
    <tr>   
        <th class="p-3 mb-2 bg-primary text-light">Complaint id</th>
        <th class="p-3 mb-2 bg-primary text-light">Subject</th>
        <th class="p-3 mb-2 bg-primary text-light">Description</th>
        <th class="p-3 mb-2 bg-primary text-light">Date Register</th>
        <th class="p-3 mb-2 bg-primary text-light">Status</th>
        <th class="p-3 mb-2 bg-primary text-light">Date Solved</th>
    </tr> 
    
    {% for i in update %}
    <tr>
            <td>{{i.id}}</td>
            <td>{{i.subject}}</td>
            <td>{{i.complaint}}</td>
            <td>{{i.rdate}}</td>
            <td>{{i.status}}</td>
            <td>{{i.sdate}}</td>
    </tr>  
    {% endfor %}

</table>
{% endblock %}

waste_management/templates/user/fullhistory.html
{% extends 'user/base.html' %}
{% block content %}
<center><h2 >Point History </h2></center>
<table class="table table-bordered table-hover">
    <tr>   
        <th class="p-3 mb-2 bg-primary text-light"> Points </th>
        <th class="p-3 mb-2 bg-primary text-light">Category </th>
        <th class="p-3 mb-2 bg-primary text-light">Weight</th>
        <th class="p-3 mb-2 bg-primary text-light">Date</th>
    </tr> 
    
    {% for i in col %}
    <tr>
           <td>{{ i.point  }}</td>
            <td>{{i.category.name}}</td>
            <td>{{i.weight}}</td>
            <td>{{i.pid.pdate}}</td>

    </tr>  
    {% endfor %}

</table>
{% endblock %}

waste_management/templates/user/history.html
{% extends 'user/base.html' %}
{% block content %}
<h1 align="center">Waste Pickup's</h1>
<table class="table table-bordered table-hover">
    <tr>   
        <th class="p-3 mb-2 bg-primary text-light"> Reqest Id</th>
        <th class="p-3 mb-2 bg-primary text-light"> Points </th>
        <th class="p-3 mb-2 bg-primary text-light">Requested Date </th>
        <th class="p-3 mb-2 bg-primary text-light">Collected Date</th>
    </tr> 
    
    {% for i in his %}
    <tr>
           <td>{{i.id}}</td>
           <td>{{ i.tpoint }}</td>
            <td>{{i.rdate}}</td>
            <td>{% if i.pdate == NULL %}
                    Not Collected
                {% else %}
                    {{i.pdate}} &nbsp; <a href="PointHistory?id={{i.id}}" class="btn-info">View Details</a>
                {% endif %}
            
            </td>

    </tr>  
    {% endfor %}

</table>
{% endblock %}

waste_management/templates/user/index.html
{% extends 'user/base.html' %}
{% block content %} 
{% load static %}
{% if message %}
<script>
  alert("{{message}}")
</script>
{% endif %}

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-info">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}
  <main class="site-main">
    
    <!--================ Hero banner start =================-->
    <section class="hero-banner">
      <div class="container">
        <div class="row no-gutters align-items-center pt-60px">
         
          <div class="col-sm-7 col-lg-6 offset-lg-1 pl-4 pl-md-5 pl-lg-0">
            <div class="hero-banner__content">
              
              <h4>Hi {{ user.name }}</h4><center>
              <div class="hero-banner__colection" >
                {% if uid.last_name == '1' %} 
              <a class="button button-hero" href="#"><img src="{% static 'img/award_star.png' %}" class='reward-icon'><p>{{ user.point }}</p>Availabe Points </a> &nbsp;&nbsp;
              {% endif %}
              </div>
              <br><br><br>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    <!--================ Hero banner start =================-->
    {% if uid.last_name == '1' %}
    <center>

      <a class="btn btn-outline-primary ms-2" href="PickupRequest">Request For Pickup</a> &nbsp;&nbsp;
      <a class="btn btn-outline-primary ms-2" href="PointHistory">Points History </a> &nbsp;&nbsp;
    </center>
    {% endif %}
    <!-- ================ offer section start ================= --> 
    <section class="offer" id="parallax-1" data-anchor-target="#parallax-1" data-300-top="background-position: 20px 30px" data-top-bottom="background-position: 0 20px">
      <div class="container">
        <div class="row">
          <div class="col-xl-5">
            <div class="offer__content text-center">
              <h4>If you are not buying recycled products,you're not really recycling</h4>
              <p>Ed Begley .Jr</p>
              
              <a class="button button--active mt-3 mt-xl-4" href="Shop">Shop Now</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ================ offer section end ================= --> 

    
  </main>

  {% endblock %}

waste_management/templates/user/joinus.html
{% extends 'user/base.html'%}
{% load static %}
{% block content %}

<section class="book_section layout_padding">
  {% if  check == True %}
    <div class="container">
      <div class="heading_container">
        <h2>
            Join Us
        </h2>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form_container">
           
            <form method="post">
              {% csrf_token %}
                <div class="form-group">
                  <label for="name">{{ user.name  }} <br> {{ user.address }} <br> {{user.pincode }} <br> +91 {{user.mobile }} </label>
                </div>
                <div class="btn_box">
                  
                    <input type="submit" value="Confirm" class="btn btn-primary" onclick="return confirm('Are you sure');">
                  </form>
                  {% else %}
                      <h5 style="color:red"> Sorry We are not avilable in you location
                  {% endif %}
              </div>
            
          </div>
        </div>
      </div>
    </section>
  {% endblock %}

waste_management/templates/user/orderhis.html
{% extends 'user/base.html' %}
{% block content %}
<table class="table table-bordered table-hover">
    <tr>   
        <th class="p-3 mb-2 bg-primary text-light">Product </th>
        <th class="p-3 mb-2 bg-primary text-light">Date </th>
        <th class="p-3 mb-2 bg-primary text-light">Payment</th>
        <th class="p-3 mb-2 bg-primary text-light">Status </th>
        <th class="p-3 mb-2 bg-primary text-light">Details </th>

    </tr> 
    
    {% for i in order %}
    <tr>
            <td>{{i.product.name}}</td>
            <td>{{i.date}}</td>
            <td>
            {% if i.type == 'R' %}
                    {{ i.total }} W-Points
                {% else %}
                    ₹ {{ i.total }}
                {% endif %}
            </td>
            <td>
                {% if i.status == 'Delivered' or i.type == 'R' %} 
                    {{i.status}} <br> <a href="Bill?id={{i.id}}" class="alert-primary">Click here to view bill</a>
                {% else %}
                    {{i.status}}
                {% endif %}
            </td>
            <td><a href="OrderUpdates?id={{i.id}}" class='btn btn-dark' >Show Details</a></td>
    </tr>  
    {% endfor %}

</table>
{% endblock %}

waste_management/templates/user/orderupdates.html
{% extends 'user/base.html' %}
{% block content %}
<table class="table table-bordered table-hover">
    <tr>   
        <th class="p-3 mb-2 bg-primary text-light">Date</th>
        <th class="p-3 mb-2 bg-primary text-light">Status</th>
        <th class="p-3 mb-2 bg-primary text-light">Description </th>
    </tr> 
    
    {% for i in update %}
    <tr>
            <td>{{i.date}}</td>
            <td>{{i.status}}</td>
            <td>{{i.update}}</td>
    </tr>  
    {% endfor %}

</table>
{% endblock %}

waste_management/templates/user/shop.html
{% extends 'user/base.html' %}
{% block content %}

<section class="section-margin calc-60px">
    <div class="container">

      <div class="section-intro pb-60px">
        <p>Popular Item in the market</p>
     </div>
     <div class="item-container">
        {% for i in prod %}
        <div class="disp">
          <div class="card text-center card-product">
            <div class="card-product__img">
              <img class="img-fluid" src="media/{{ i.image }}" alt="{{i.image}}">
              <ul class="card-product__imgOverlay" 
                <li><a href="Product?id={{ i.id }}" class='btn btn-danger'></i>Purchase</a></li>
              </ul>
            </div>
            <div class="card-body" >
              <h4 class="card-product__title"><a href="Product?id={{ i.id }}">{{ i.name }}</a></h4>
              <p ><span class="material-symbols-outlined"></span>₹ {{i.rate}}</i></p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>

      
    </div>
  </section>
  {% endblock %}